# Generated by Django 3.0.6 on 2020-05-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.IntegerField(verbose_name='Metai')),
                ('marke', models.CharField(max_length=200, verbose_name='Markė')),
                ('modelis', models.CharField(max_length=200, verbose_name='Modelis')),
                ('variklis', models.CharField(max_length=200, verbose_name='Variklis')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savininkas', models.CharField(max_length=200, verbose_name='Savininkas')),
                ('valstybinis_numeris', models.CharField(max_length=200, verbose_name='Valstybinis numeris')),
                ('vin_kodas', models.CharField(max_length=200, verbose_name='VIN kodas')),
                ('automobilio_modelis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.FloatField(verbose_name='Suma')),
                ('automobilis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Automobilis')),
            ],
        ),
        migrations.RenameModel(
            old_name='Paslaugos',
            new_name='Paslauga',
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(verbose_name='Kiekis')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
                ('paslauga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Paslauga')),
                ('uzsakymas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Uzsakymas')),
            ],
        ),
        migrations.CreateModel(
            name='Paslaugos_kaina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
                ('automobilis_ids', models.ManyToManyField(help_text='Išrinkite žanrą(us) šiai knygai', to='autoservice.Automobilio_modelis')),
                ('paslauga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Paslauga')),
            ],
        ),
    ]
