# Generated by Django 3.0.6 on 2020-05-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_auto_20200518_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga'},
        ),
    ]
